name: Publish
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Publish plugin
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      shell: bash
      run: git archive --format=zip --prefix="marmot-theme-child/" HEAD > marmot-theme-child.zip
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: marmot-theme-child.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: "Release"
